### ISSUE TITLE
Create 4 Mockup Pages (M1)

### ISSUE THREAD

**Issue by TravisQuesenberry** [campuscravings/manoa-campus-cravings#3]
Do all work for this task in a branch called issue-03.
Create the following 4 mockup pages:

- Homepage (USER, OWNR, ADMIN)
- User Profile Page
- Login Pages (USER, OWNR, ADMIN)
- List Restaurant page

**Comment by TravisQuesenberry** [comment]
Can interchange with other page ideas as needed

**Comment by qckapiu** [comment]
I've separated these into separate issues for the presentation on Wednesday. Will be moving this issue to closed
