### ISSUE TITLE
Publish the project home page in the newly created repo "cc-home"

### ISSUE THREAD

**Issue by qckapiu** [campuscravings/manoa-campus-cravings#6]
Do all work for this task in a branch called issue-06

According to the assignment:

"Created a GitHub organization for your project, with two repos: one that provides the home page for your organization, and one that provides the source code for your application."

A separate repo named cc-home has been added to the organization campuscravings.  Could someone republish the project home page from the new repo instead in order to follow the project requirements? The index.md file has already been copied to the new repo "cc-home". "manoa-campus-cravings" will be the repo used for the source code.

**Comment by kylebueche** [comment]
Woooooooooo page is up
